AllCops:
  DisabledDefault: true
Layout/LineLength:
  Max: 80
Metrics/ParameterLists:
  Max: 3
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10
Lint/Debugger:
  Enabled: true

Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
Security/Open:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
